# Generated by Django 4.2.7 on 2024-03-05 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_conversation_created_at_conversation_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='created_at',
            new_name='last_updated',
        ),
    ]
